[project]
name = "pydonut"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ASDAlexander77", email = "duzhar@googlemail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pybind11>=3.0.4",
]

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.{h,c,hpp,cpp}" }, { file = "CMakeLists.txt" }]

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build.cmake.define]
PYNRI_ENABLE_D3D12 = "ON"
PYNRI_ENABLE_VULKAN = "ON"

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
search_path = [
    "src",
    "test",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
