#ifndef LIGHTING_CB_H
#define LIGHTING_CB_H

#include <donut/shaders/light_cb.h>
#include <donut/shaders/view_cb.h>

#define REFLECTIONS_SPACE_GLOBAL                    0
#define REFLECTIONS_BINDING_MATERIAL_SAMPLER        0
#define REFLECTIONS_BINDING_LIGHTING_CONSTANTS      0
#define REFLECTIONS_BINDING_OUTPUT_UAV              0
#define REFLECTIONS_BINDING_SCENE_BVH               0
#define REFLECTIONS_BINDING_GBUFFER_DEPTH_TEXTURE   1
#define REFLECTIONS_BINDING_GBUFFER_0_TEXTURE       2
#define REFLECTIONS_BINDING_GBUFFER_1_TEXTURE       3
#define REFLECTIONS_BINDING_GBUFFER_2_TEXTURE       4
#define REFLECTIONS_BINDING_GBUFFER_3_TEXTURE       5

#define REFLECTIONS_SPACE_LOCAL                     1
#define REFLECTIONS_BINDING_MATERIAL_CONSTANTS      0
#define REFLECTIONS_BINDING_INDEX_BUFFER            0
#define REFLECTIONS_BINDING_TEX_COORD_BUFFER        1
#define REFLECTIONS_BINDING_NORMAL_BUFFER           2
#define REFLECTIONS_BINDING_DIFFUSE_TEXTURE         3
#define REFLECTIONS_BINDING_SPECULAR_TEXTURE        4
#define REFLECTIONS_BINDING_NORMAL_TEXTURE          5
#define REFLECTIONS_BINDING_EMISSIVE_TEXTURE        6
#define REFLECTIONS_BINDING_OCCLUSION_TEXTURE       7
#define REFLECTIONS_BINDING_TRANSMISSION_TEXTURE    8
#define REFLECTIONS_BINDING_OPACITY_TEXTURE         9

struct LightingConstants
{
    float4 ambientColor;

    LightConstants light;
    PlanarViewConstants view;
};

#endif // LIGHTING_CB_H
