from enum import Enum
from pathlib import Path
from typing import Callable, Optional, overload

class GraphicsAPI(Enum):
    D3D11 = 0
    D3D12 = 1
    Vulkan = 2

class Format(Enum):
    UNKNOWN = 0
    R8_UINT = 1
    R8_SINT = 2
    R8_UNORM = 3
    R8_SNORM = 4
    RG8_UINT = 5
    RG8_SINT = 6
    RG8_UNORM = 7
    RG8_SNORM = 8
    R16_UINT = 9
    R16_SINT = 10
    R16_UNORM = 11
    R16_SNORM = 12
    R16_FLOAT = 13
    BGRA4_UNORM = 14
    B5G6R5_UNORM = 15
    B5G5R5A1_UNORM = 16
    RGBA8_UINT = 17
    RGBA8_SINT = 18
    RGBA8_UNORM = 19
    RGBA8_SNORM = 20
    BGRA8_UNORM = 21
    BGRX8_UNORM = 22
    SRGBA8_UNORM = 23
    SBGRA8_UNORM = 24
    SBGRX8_UNORM = 25
    R10G10B10A2_UNORM = 26
    R11G11B10_FLOAT = 27
    RG16_UINT = 28
    RG16_SINT = 29
    RG16_UNORM = 30
    RG16_SNORM = 31
    RG16_FLOAT = 32
    R32_UINT = 33
    R32_SINT = 34
    R32_FLOAT = 35
    RGBA16_UINT = 36
    RGBA16_SINT = 37
    RGBA16_FLOAT = 38
    RGBA16_UNORM = 39
    RGBA16_SNORM = 40
    RG32_UINT = 41
    RG32_SINT = 42
    RG32_FLOAT = 43
    RGB32_UINT = 44
    RGB32_SINT = 45
    RGB32_FLOAT = 46
    RGBA32_UINT = 47
    RGBA32_SINT = 48
    RGBA32_FLOAT = 49
    D16 = 50
    D24S8 = 51
    X24G8_UINT = 52
    D32 = 53
    D32S8 = 54
    X32G8_UINT = 55
    BC1_UNORM = 56
    BC1_UNORM_SRGB = 57
    BC2_UNORM = 58
    BC2_UNORM_SRGB = 59
    BC3_UNORM = 60
    BC3_UNORM_SRGB = 61
    BC4_UNORM = 62
    BC4_SNORM = 63
    BC5_UNORM = 64
    BC5_SNORM = 65
    BC6H_UFLOAT = 66
    BC6H_SFLOAT = 67
    BC7_UNORM = 68
    BC7_UNORM_SRGB = 69
    COUNT = 70

class LogSeverity(Enum):
    None_ = 0
    Debug = 1
    Info = 2
    Warning = 3
    Error = 4
    Fatal = 5

class ShaderType(Enum):
    None_ = 0x0000
    Compute = 0x0020
    Vertex = 0x0001
    Hull = 0x0002
    Domain = 0x0004
    Geometry = 0x0008
    Pixel = 0x0010
    Amplification = 0x0040
    Mesh = 0x0080
    AllGraphics = 0x00DF
    RayGeneration = 0x0100
    AnyHit = 0x0200
    ClosestHit = 0x0400
    Miss = 0x0800
    Intersection = 0x1000
    Callable = 0x2000
    AllRayTracing = 0x3F00
    All = 0x3FFF

class PrimitiveType(Enum):
    PointList = 0
    LineList = 1
    LineStrip = 2
    TriangleList = 3
    TriangleStrip = 4
    TriangleFan = 5
    TriangleListWithAdjacency = 6
    TriangleStripWithAdjacency = 7
    PatchList = 8

class ComparisonFunc(Enum):
    Never = 1
    Less = 2
    Equal = 3
    LessOrEqual = 4
    Greater = 5
    NotEqual = 6
    GreaterOrEqual = 7
    Always = 8

class RasterCullMode(Enum):
    Back = 0
    Front = 1
    None_ = 2

class CommandQueue(Enum):
    Graphics = 0
    Compute = 1
    Copy = 2

class Feature(Enum):
    ComputeQueue = 0
    ConservativeRasterization = 1
    ConstantBufferRanges = 2
    CopyQueue = 3
    DeferredCommandLists = 4
    FastGeometryShader = 5
    HeapDirectlyIndexed = 6
    HlslExtensionUAV = 7
    LinearSweptSpheres = 8
    Meshlets = 9
    RayQuery = 10
    RayTracingAccelStruct = 11
    RayTracingClusters = 12
    RayTracingOpacityMicromap = 13
    RayTracingPipeline = 14
    SamplerFeedback = 15
    ShaderExecutionReordering = 16
    ShaderSpecializations = 17
    SinglePassStereo = 18
    Spheres = 19
    VariableRateShading = 20
    VirtualResources = 21
    WaveLaneCountMinMax = 22
    CooperativeVectorInferencing = 23
    CooperativeVectorTraining = 24
    EnhancedBarriers = 25

class ResourceStates(Enum):
    Unknown = 0x00000000
    Common = 0x00000001
    ConstantBuffer = 0x00000002
    VertexBuffer = 0x00000004
    IndexBuffer = 0x00000008
    IndirectArgument = 0x00000010
    PixelShaderResource = 0x00000020
    NonPixelShaderResource = 0x00000040
    ShaderResource = 0x00000060
    UnorderedAccess = 0x00000080
    RenderTarget = 0x00000100
    DepthWrite = 0x00000200
    DepthRead = 0x00000400
    StreamOut = 0x00000800
    CopyDest = 0x00001000
    CopySource = 0x00002000
    ResolveDest = 0x00004000
    ResolveSource = 0x00008000
    Present = 0x00010000
    AccelStructRead = 0x00020000
    AccelStructWrite = 0x00040000
    AccelStructBuildInput = 0x00080000
    AccelStructBuildBlas = 0x00100000
    ShadingRateSurface = 0x00200000
    OpacityMicromapWrite = 0x00400000
    OpacityMicromapBuildInput = 0x00800000
    ConvertCoopVecMatrixInput = 0x01000000
    ConvertCoopVecMatrixOutput = 0x02000000

class GeometryFlags(Enum):
    None_ = 0
    Opaque = 1
    NoDuplicateAnyHitInvocation = 2

class InstanceFlags(Enum):
    None_ = 0
    TriangleCullDisable = 1
    TriangleFrontCounterclockwise = 2
    ForceOpaque = 4
    ForceNonOpaque = 8
    ForceOMM2State = 16
    DisableOMMs = 32

def GetGraphicsAPIFromCommandLine(args: list[str]) -> GraphicsAPI: ...
def GetDirectoryWithExecutable() -> Path: ...
def GetShaderTypeName(api: GraphicsAPI) -> str: ...
def ClearColorAttachment(commandList: CommandList, framebuffer: Framebuffer, attachmentIndex: int, color: Color) -> None: ...

class log():
    @staticmethod
    def SetMinSeverity(severity: LogSeverity) -> None: ...
    @staticmethod
    def SetCallback(callback: Callable[[LogSeverity, str], None]) -> None: ...
    @staticmethod
    def ResetCallback() -> None: ...
    @staticmethod
    def EnableOutputToMessageBox(enable: bool) -> None: ...
    @staticmethod
    def EnableOutputToConsole(enable: bool) -> None: ...
    @staticmethod
    def EnableOutputToDebug(enable: bool) -> None: ...
    @staticmethod
    def SetErrorMessageCaption(caption: str) -> None: ...
    @staticmethod
    def ConsoleApplicationMode() -> None: ...
    @staticmethod
    def message(severity: LogSeverity, message: str) -> None: ...
    @staticmethod
    def debug(message: str) -> None: ...
    @staticmethod
    def info(message: str) -> None: ...
    @staticmethod
    def warning(message: str) -> None: ...
    @staticmethod
    def error(message: str) -> None: ...
    # Aborts the process by default (Donut's DefaultCallback behavior) after logging;
    # install a custom callback via Log.SetCallback first if that's not desired.
    @staticmethod
    def fatal(message: str) -> None: ...

# In-process HLSL -> DXIL/SPIR-V compilation via DXC. Not available in every build
# (requires DXC to have been found at configure time); raises RuntimeError on a
# compile error, with DXC's diagnostic text as the message.
def CompileShader(
    source: str,
    entryPoint: str,
    shaderType: ShaderType,
    api: GraphicsAPI,
    sourceName: str = "shader.hlsl",
    shaderModel: str = "6_5",
    includePaths: list[str] = [],
) -> bytes: ...

# Same as CompileShader, but for a shader library with multiple [shader("...")]-annotated
# exports (e.g. a DXR raygen/closesthit/miss set) instead of a single entry point. Feed the
# result to Device.createShaderLibrary.
def CompileShaderLibrary(
    source: str,
    api: GraphicsAPI,
    sourceName: str = "shader.hlsl",
    shaderModel: str = "6_5",
    includePaths: list[str] = [],
) -> bytes: ...

class Color():
    r: float
    g: float
    b: float
    a: float
    @overload
    def __init__(self: Color) -> None: ...
    @overload
    def __init__(self: Color, c: float) -> None: ...
    @overload
    def __init__(self: Color, r: float, g: float, b: float, a: float) -> None: ...

class Viewport():
    minX: float
    maxX: float
    minY: float
    maxY: float
    minZ: float
    maxZ: float
    @overload
    def __init__(self: Viewport) -> None: ...
    @overload
    def __init__(self: Viewport, width: float, height: float) -> None: ...
    @overload
    def __init__(self: Viewport, minX: float, maxX: float, minY: float, maxY: float, minZ: float, maxZ: float) -> None: ...
    def width(self: Viewport) -> float: ...
    def height(self: Viewport) -> float: ...

class ViewportState():
    def __init__(self: ViewportState) -> None: ...
    def addViewportAndScissorRect(self: ViewportState, viewport: Viewport) -> None: ...

class FramebufferInfo():
    depthFormat: Format
    sampleCount: int
    sampleQuality: int
    width: int
    height: int
    arraySize: int
    def getViewport(self: FramebufferInfo, minZ: float = 0.0, maxZ: float = 1.0) -> Viewport: ...

class DepthStencilState():
    depthTestEnable: bool
    depthFunc: ComparisonFunc
    def __init__(self: DepthStencilState) -> None: ...

class RasterState():
    cullMode: RasterCullMode
    frontCounterClockwise: bool
    def __init__(self: RasterState) -> None: ...

class RenderState():
    depthStencilState: DepthStencilState
    rasterState: RasterState
    def __init__(self: RenderState) -> None: ...

class DrawArguments():
    vertexCount: int
    instanceCount: int
    startIndexLocation: int
    startVertexLocation: int
    startInstanceLocation: int
    def __init__(self: DrawArguments) -> None: ...

class GraphicsPipelineDesc():
    primType: PrimitiveType
    renderState: RenderState
    VS: Optional[Shader]
    PS: Optional[Shader]
    def __init__(self: GraphicsPipelineDesc) -> None: ...
    def addBindingLayout(self: GraphicsPipelineDesc, layout: BindingLayout) -> None: ...

class GraphicsState():
    viewport: ViewportState
    pipeline: Optional[GraphicsPipeline]
    framebuffer: Optional[Framebuffer]
    def __init__(self: GraphicsState) -> None: ...
    def addBindingSet(self: GraphicsState, bindingSet: BindingSet) -> None: ...

class MeshletPipelineDesc():
    primType: PrimitiveType
    renderState: RenderState
    AS: Optional[Shader]
    MS: Optional[Shader]
    PS: Optional[Shader]
    def __init__(self: MeshletPipelineDesc) -> None: ...

class MeshletState():
    viewport: ViewportState
    pipeline: Optional[MeshletPipeline]
    framebuffer: Optional[Framebuffer]
    def __init__(self: MeshletState) -> None: ...

class BufferDesc():
    byteSize: int
    structStride: int
    maxVersions: int
    debugName: str
    format: Format
    canHaveUAVs: bool
    canHaveTypedViews: bool
    canHaveRawViews: bool
    isVertexBuffer: bool
    isIndexBuffer: bool
    isConstantBuffer: bool
    isDrawIndirectArgs: bool
    isAccelStructBuildInput: bool
    isAccelStructStorage: bool
    isShaderBindingTable: bool
    isVolatile: bool
    initialState: ResourceStates
    keepInitialState: bool
    def __init__(self: BufferDesc) -> None: ...

class TextureDesc():
    width: int
    height: int
    depth: int
    arraySize: int
    mipLevels: int
    sampleCount: int
    format: Format
    debugName: str
    isShaderResource: bool
    isRenderTarget: bool
    isUAV: bool
    clearValue: Color
    useClearValue: bool
    initialState: ResourceStates
    keepInitialState: bool
    def __init__(self: TextureDesc) -> None: ...

class FramebufferAttachment():
    texture: Optional[Texture]

class FramebufferDesc():
    def __init__(self: FramebufferDesc) -> None: ...
    def getColorAttachment(self: FramebufferDesc, index: int) -> FramebufferAttachment: ...
    def addColorAttachment(self: FramebufferDesc, attachment: FramebufferAttachment) -> None: ...
    def setDepthAttachment(self: FramebufferDesc, texture: Texture) -> None: ...

# BindingLayoutItem/BindingSetItem are opaque -- Python only obtains instances through
# these static factories, matching how nvrhi's own C++ call sites construct them.
class BindingLayoutItem():
    @staticmethod
    def Texture_UAV(slot: int) -> BindingLayoutItem: ...
    @staticmethod
    def Texture_SRV(slot: int) -> BindingLayoutItem: ...
    @staticmethod
    def RawBuffer_SRV(slot: int) -> BindingLayoutItem: ...
    @staticmethod
    def RayTracingAccelStruct(slot: int) -> BindingLayoutItem: ...

class BindingLayoutDesc():
    visibility: ShaderType
    bindings: list[BindingLayoutItem]
    def __init__(self: BindingLayoutDesc) -> None: ...

class BindingSetItem():
    @staticmethod
    def Texture_UAV(slot: int, texture: Texture) -> BindingSetItem: ...
    @staticmethod
    def RayTracingAccelStruct(slot: int, accelStruct: AccelStruct) -> BindingSetItem: ...
    @staticmethod
    def ConstantBuffer(slot: int, buffer: Buffer) -> BindingSetItem: ...
    @staticmethod
    def StructuredBuffer_SRV(slot: int, buffer: Buffer) -> BindingSetItem: ...
    @staticmethod
    def Sampler(slot: int, sampler: Sampler) -> BindingSetItem: ...
    @staticmethod
    def PushConstants(slot: int, byteSize: int) -> BindingSetItem: ...

class BindingSetDesc():
    bindings: list[BindingSetItem]
    def __init__(self: BindingSetDesc) -> None: ...

# BindlessLayoutDesc.registerSpaces reuses BindingLayoutItem, but its slot argument means
# "register space index" here rather than a binding slot -- e.g. RawBuffer_SRV(1) assigns
# space 1 to a ByteAddressBuffer descriptor array.
class BindlessLayoutDesc():
    visibility: ShaderType
    firstSlot: int
    maxCapacity: int
    def __init__(self: BindlessLayoutDesc) -> None: ...
    def addRegisterSpace(self: BindlessLayoutDesc, item: BindingLayoutItem) -> None: ...

def CreateVolatileConstantBufferDesc(byteSize: int, debugName: str, maxVersions: int) -> BufferDesc: ...
def CreateBindingSetAndLayout(device: Device, visibility: ShaderType, registerSpace: int, bindingSetDesc: BindingSetDesc) -> tuple[BindingLayout, BindingSet]: ...
def ClearDepthStencilAttachment(commandList: CommandList, framebuffer: Framebuffer, depth: float, stencil: int) -> None: ...

class GeometryTriangles():
    indexBuffer: Optional[Buffer]
    vertexBuffer: Optional[Buffer]
    indexFormat: Format
    vertexFormat: Format
    indexCount: int
    vertexCount: int
    vertexStride: int
    def __init__(self: GeometryTriangles) -> None: ...

class GeometryDesc():
    flags: GeometryFlags
    def __init__(self: GeometryDesc) -> None: ...
    def setTriangles(self: GeometryDesc, triangles: GeometryTriangles) -> None: ...

class AccelStructDesc():
    isTopLevel: bool
    topLevelMaxInstances: int
    bottomLevelGeometries: list[GeometryDesc]
    def __init__(self: AccelStructDesc) -> None: ...

# InstanceDesc packs bitfields + a union, so it's mutated through setter methods rather
# than plain properties. The default constructor already fills in the identity transform.
class InstanceDesc():
    def __init__(self: InstanceDesc) -> None: ...
    def setInstanceMask(self: InstanceDesc, value: int) -> None: ...
    def setInstanceID(self: InstanceDesc, value: int) -> None: ...
    def setInstanceContributionToHitGroupIndex(self: InstanceDesc, value: int) -> None: ...
    def setFlags(self: InstanceDesc, value: InstanceFlags) -> None: ...
    def setBLAS(self: InstanceDesc, value: AccelStruct) -> None: ...

class PipelineShaderDesc():
    def __init__(self: PipelineShaderDesc) -> None: ...
    def setShader(self: PipelineShaderDesc, shader: Shader) -> None: ...

class PipelineHitGroupDesc():
    def __init__(self: PipelineHitGroupDesc) -> None: ...
    def setExportName(self: PipelineHitGroupDesc, value: str) -> None: ...
    def setClosestHitShader(self: PipelineHitGroupDesc, shader: Shader) -> None: ...

class RayTracingPipelineDesc():
    maxPayloadSize: int
    def __init__(self: RayTracingPipelineDesc) -> None: ...
    def addShader(self: RayTracingPipelineDesc, shader: PipelineShaderDesc) -> None: ...
    def addHitGroup(self: RayTracingPipelineDesc, hitGroup: PipelineHitGroupDesc) -> None: ...
    def addBindingLayout(self: RayTracingPipelineDesc, layout: BindingLayout) -> None: ...

class RayTracingState():
    shaderTable: Optional[ShaderTable]
    def __init__(self: RayTracingState) -> None: ...
    def addBindingSet(self: RayTracingState, bindingSet: BindingSet) -> None: ...

class DispatchRaysArguments():
    width: int
    height: int
    depth: int
    def __init__(self: DispatchRaysArguments) -> None: ...

# Swap-chain resources: owned by the DeviceManager, never constructible from Python.
class Framebuffer():
    def getFramebufferInfo(self: Framebuffer) -> FramebufferInfo: ...
    def getDesc(self: Framebuffer) -> FramebufferDesc: ...

# Texture wraps both borrowed (swap-chain) and owned (Device.createTexture) instances.
class Texture():
    def getDesc(self: Texture) -> TextureDesc: ...

# Objects created through Device / ShaderFactory factory calls.
class Shader(): ...
class ShaderLibrary():
    def getShader(self: ShaderLibrary, entryName: str, shaderType: ShaderType) -> Optional[Shader]: ...
class GraphicsPipeline(): ...
class MeshletPipeline(): ...
class RayTracingPipeline():
    def createShaderTable(self: RayTracingPipeline) -> ShaderTable: ...
class ShaderTable():
    def setRayGenerationShader(self: ShaderTable, exportName: str, bindings: Optional[BindingSet] = None) -> None: ...
    def addHitGroup(self: ShaderTable, exportName: str, bindings: Optional[BindingSet] = None) -> int: ...
    def addMissShader(self: ShaderTable, exportName: str, bindings: Optional[BindingSet] = None) -> int: ...
class CommandList():
    def open(self: CommandList) -> None: ...
    def close(self: CommandList) -> None: ...
    def setGraphicsState(self: CommandList, state: GraphicsState) -> None: ...
    def draw(self: CommandList, args: DrawArguments) -> None: ...
    def setMeshletState(self: CommandList, state: MeshletState) -> None: ...
    def dispatchMesh(self: CommandList, groupsX: int, groupsY: int = 1, groupsZ: int = 1) -> None: ...
    def writeBuffer(self: CommandList, buffer: Buffer, data: bytes, destOffsetBytes: int = 0) -> None: ...
    def buildTopLevelAccelStruct(self: CommandList, as_: AccelStruct, instances: list[InstanceDesc]) -> None: ...
    def setRayTracingState(self: CommandList, state: RayTracingState) -> None: ...
    def dispatchRays(self: CommandList, args: DispatchRaysArguments) -> None: ...
    def setPushConstants(self: CommandList, data: bytes) -> None: ...
    def clearTextureFloat(self: CommandList, texture: Texture, clearColor: Color) -> None: ...
    def clearDepthStencilTexture(self: CommandList, texture: Texture, clearDepth: bool, depth: float, clearStencil: bool, stencil: int) -> None: ...
class Buffer(): ...
class BindingLayout(): ...
class BindingSet(): ...
class Sampler(): ...
class AccelStruct(): ...

class Device():
    def getGraphicsAPI(self: Device) -> GraphicsAPI: ...
    def createCommandList(self: Device) -> CommandList: ...
    def createGraphicsPipeline(self: Device, desc: GraphicsPipelineDesc, framebufferInfo: FramebufferInfo) -> GraphicsPipeline: ...
    def createMeshletPipeline(self: Device, desc: MeshletPipelineDesc, framebufferInfo: FramebufferInfo) -> MeshletPipeline: ...
    def executeCommandList(self: Device, commandList: CommandList, executionQueue: CommandQueue = CommandQueue.Graphics) -> int: ...
    def createShader(self: Device, bytecode: bytes, entryName: str, shaderType: ShaderType) -> Optional[Shader]: ...
    def queryFeatureSupport(self: Device, feature: Feature) -> bool: ...
    def createBuffer(self: Device, desc: BufferDesc) -> Buffer: ...
    def createTexture(self: Device, desc: TextureDesc) -> Texture: ...
    def createFramebuffer(self: Device, desc: FramebufferDesc) -> Framebuffer: ...
    def createBindingLayout(self: Device, desc: BindingLayoutDesc) -> BindingLayout: ...
    def createBindingSet(self: Device, desc: BindingSetDesc, layout: BindingLayout) -> BindingSet: ...
    def createBindlessLayout(self: Device, desc: BindlessLayoutDesc) -> BindingLayout: ...
    def createAccelStruct(self: Device, desc: AccelStructDesc) -> AccelStruct: ...
    def createRayTracingPipeline(self: Device, desc: RayTracingPipelineDesc) -> RayTracingPipeline: ...
    def createShaderLibrary(self: Device, bytecode: bytes) -> Optional[ShaderLibrary]: ...
    def waitForIdle(self: Device) -> None: ...

def BuildBottomLevelAccelStruct(commandList: CommandList, as_: AccelStruct, desc: AccelStructDesc) -> None: ...

class IFileSystem(): ...
class NativeFileSystem(IFileSystem):
    def __init__(self: NativeFileSystem) -> None: ...
class RootFileSystem(IFileSystem):
    def __init__(self: RootFileSystem) -> None: ...
    def mount(self: RootFileSystem, path: Path, nativePath: Path) -> None: ...

class ShaderFactory():
    def __init__(self: ShaderFactory, device: Device, fs: IFileSystem, basePath: Path) -> None: ...
    def CreateShader(self: ShaderFactory, fileName: str, entryName: str, shaderType: ShaderType) -> Optional[Shader]: ...
    def CreateShaderLibrary(self: ShaderFactory, fileName: str) -> Optional[ShaderLibrary]: ...

class BindingCache():
    def __init__(self: BindingCache, device: Device) -> None: ...
    def Clear(self: BindingCache) -> None: ...

class CommonRenderPasses():
    def __init__(self: CommonRenderPasses, device: Device, shaderFactory: ShaderFactory) -> None: ...
    def BlitTexture(self: CommonRenderPasses, commandList: CommandList, targetFramebuffer: Framebuffer, sourceTexture: Texture, bindingCache: Optional[BindingCache] = None) -> None: ...
    m_AnisotropicWrapSampler: Sampler

class DescriptorTableManager():
    def __init__(self: DescriptorTableManager, device: Device, layout: BindingLayout) -> None: ...
    def GetDescriptorTable(self: DescriptorTableManager) -> BindingSet: ...

class TextureCache():
    def __init__(self: TextureCache, device: Device, fs: IFileSystem, descriptorTable: DescriptorTableManager) -> None: ...
    def Reset(self: TextureCache) -> None: ...
    def ProcessRenderingThreadCommands(self: TextureCache, commonPasses: CommonRenderPasses, timeLimitMilliseconds: float) -> bool: ...
    def LoadingFinished(self: TextureCache) -> None: ...

class Scene():
    def __init__(self: Scene, device: Device, shaderFactory: ShaderFactory, fs: IFileSystem, textureCache: TextureCache, descriptorTable: DescriptorTableManager) -> None: ...
    def Load(self: Scene, sceneFileName: str) -> bool: ...
    def FinishedLoading(self: Scene, frameIndex: int) -> None: ...
    def GetInstanceBuffer(self: Scene) -> Buffer: ...
    def GetGeometryBuffer(self: Scene) -> Buffer: ...
    def GetMaterialBuffer(self: Scene) -> Buffer: ...
    # Flattened (instanceIndex, geometryIndexInMesh, numIndices) per drawable geometry.
    def GetDrawItems(self: Scene) -> list[tuple[int, int, int]]: ...

# Mirrors ApplicationBase::SceneLoaded()'s synchronous-load finalization step. Call after
# Scene.Load() and before Scene.FinishedLoading().
def SceneLoaded(textureCache: TextureCache, commonPasses: CommonRenderPasses) -> None: ...

class FirstPersonCamera():
    def __init__(self: FirstPersonCamera) -> None: ...
    def LookAt(self: FirstPersonCamera, posX: float, posY: float, posZ: float, targetX: float, targetY: float, targetZ: float) -> None: ...
    def SetMoveSpeed(self: FirstPersonCamera, value: float) -> None: ...
    def Animate(self: FirstPersonCamera, deltaT: float) -> None: ...
    def KeyboardUpdate(self: FirstPersonCamera, key: int, scancode: int, action: int, mods: int) -> None: ...
    def MousePosUpdate(self: FirstPersonCamera, xpos: float, ypos: float) -> None: ...
    def MouseButtonUpdate(self: FirstPersonCamera, button: int, action: int, mods: int) -> None: ...

class PlanarView():
    def __init__(self: PlanarView) -> None: ...
    def SetViewport(self: PlanarView, viewport: Viewport) -> None: ...
    # Builds the view/projection matrices from the camera internally (they aren't exposed
    # to Python) via perspProjD3DStyleReverse(verticalFovRadians, aspectRatio, zNear).
    def SetMatricesFromCamera(self: PlanarView, camera: FirstPersonCamera, aspectRatio: float, verticalFovRadians: float = ..., zNear: float = 0.1) -> None: ...
    def UpdateCache(self: PlanarView) -> None: ...
    def GetViewportState(self: PlanarView) -> ViewportState: ...
    # Raw bytes of the engine's PlanarViewConstants struct, ready for CommandList.writeBuffer.
    def FillPlanarViewConstants(self: PlanarView) -> bytes: ...

class AdapterInfo():
    name: str
    vendorID: int
    deviceID: int
    dedicatedVideoMemory: int
    uuid: Optional[list[int]]
    luid: Optional[list[int]]

class IRenderPass():
    def __init__(self: IRenderPass, deviceManager: DeviceManager) -> None: ...
    def SetLatewarpOptions(self: IRenderPass) -> None: ...
    def ShouldAnimateUnfocused(self: IRenderPass) -> bool: ...
    def ShouldRenderUnfocused(self: IRenderPass) -> bool: ...
    def SupportsDepthBuffer(self: IRenderPass) -> bool: ...
    def Render(self: IRenderPass, framebuffer: Framebuffer) -> None: ...
    def Animate(self: IRenderPass, elapsedTimeSeconds: float) -> None: ...
    def BackBufferResizing(self: IRenderPass) -> None: ...
    def BackBufferResized(self: IRenderPass, width: int, height: int, sampleCount: int) -> None: ...
    def DisplayScaleChanged(self: IRenderPass, scaleX: float, scaleY: float) -> None: ...
    def KeyboardUpdate(self: IRenderPass, key: int, scancode: int, action: int, mods: int) -> bool: ...
    def KeyboardCharInput(self: IRenderPass, unicode: int, mods: int) -> bool: ...
    def MousePosUpdate(self: IRenderPass, xpos: float, ypos: float) -> bool: ...
    def MouseScrollUpdate(self: IRenderPass, xoffset: float, yoffset: float) -> bool: ...
    def MouseButtonUpdate(self: IRenderPass, button: int, action: int, mods: int) -> bool: ...
    def JoystickButtonUpdate(self: IRenderPass, button: int, pressed: bool) -> bool: ...
    def JoystickAxisUpdate(self: IRenderPass, axis: int, value: float) -> bool: ...
    def GetDeviceManager(self: IRenderPass) -> DeviceManager: ...
    def GetDevice(self: IRenderPass) -> Device: ...
    def GetFrameIndex(self: IRenderPass) -> int: ...

class ApplicationBase(IRenderPass):
    def __init__(self: ApplicationBase, deviceManager: DeviceManager) -> None: ...
    def RenderScene(self: ApplicationBase, framebuffer: Framebuffer) -> None: ...
    def RenderSplashScreen(self: ApplicationBase, framebuffer: Framebuffer) -> None: ...
    def BeginLoadingScene(self: ApplicationBase, fs: IFileSystem, sceneFileName: str) -> None: ...
    def LoadScene(self: ApplicationBase, fs: IFileSystem, sceneFileName: str) -> bool: ...
    def SceneUnloading(self: ApplicationBase) -> None: ...
    def SceneLoaded(self: ApplicationBase) -> None: ...
    def SetAsynchronousLoadingEnabled(self: ApplicationBase, enabled: bool) -> None: ...
    def IsSceneLoading(self: ApplicationBase) -> bool: ...
    def IsSceneLoaded(self: ApplicationBase) -> bool: ...
    def GetCommonPasses(self: ApplicationBase) -> CommonRenderPasses: ...

class PipelineCallbacks():
    beforeFrame: Optional[Callable[[DeviceManager, int], None]]
    beforeAnimate: Optional[Callable[[DeviceManager, int], None]]
    afterAnimate: Optional[Callable[[DeviceManager, int], None]]
    beforeRender: Optional[Callable[[DeviceManager, int], None]]
    afterRender: Optional[Callable[[DeviceManager, int], None]]
    beforePresent: Optional[Callable[[DeviceManager, int], None]]
    afterPresent: Optional[Callable[[DeviceManager, int], None]]

class DeviceCreationParameters():
    # InstanceParameters (base class)
    enableDebugRuntime: bool
    enableWarningsAsErrors: bool
    enableGPUValidation: bool
    headlessDevice: bool
    logBufferLifetime: bool
    enableHeapDirectlyIndexed: bool
    enablePerMonitorDPI: bool
    infoLogSeverity: LogSeverity
    vulkanLibraryName: str
    requiredVulkanInstanceExtensions: list[str]
    requiredVulkanLayers: list[str]
    optionalVulkanInstanceExtensions: list[str]
    optionalVulkanLayers: list[str]

    # DeviceCreationParameters
    startMaximized: bool
    startFullscreen: bool
    startBorderless: bool
    fullscreenAlwaysOnTop: bool
    windowPosX: int
    windowPosY: int
    backBufferWidth: int
    backBufferHeight: int
    refreshRate: int
    swapChainBufferCount: int
    swapChainFormat: Format
    swapChainSampleCount: int
    swapChainSampleQuality: int
    depthBufferFormat: Format
    maxFramesInFlight: int
    enableNvrhiValidationLayer: bool
    enableRayTracingValidation: bool
    vsyncEnabled: bool
    enableRayTracingExtensions: bool
    enableComputeQueue: bool
    enableCopyQueue: bool
    adapterIndex: int
    supportExplicitDisplayScaling: bool
    resizeWindowWithDisplayScale: bool
    swapChainUsage: int
    featureLevel: int
    requiredVulkanDeviceExtensions: list[str]
    optionalVulkanDeviceExtensions: list[str]
    ignoredVulkanValidationMessageLocations: list[int]

class DeviceManager():
    callbacks: PipelineCallbacks

    @staticmethod
    def Create(api: GraphicsAPI = GraphicsAPI.Vulkan) -> DeviceManager: ...
    def CreateHeadlessDevice(self: DeviceManager, params: DeviceCreationParameters) -> bool: ...
    def CreateWindowDeviceAndSwapChain(self: DeviceManager, params: DeviceCreationParameters, windowTitle: str = "") -> bool: ...
    def CreateInstance(self: DeviceManager, params: DeviceCreationParameters) -> bool: ...
    def EnumerateAdapters(self: DeviceManager) -> tuple[bool, list[AdapterInfo]]: ...
    def AddRenderPassToFront(self: DeviceManager, renderPass: IRenderPass) -> None: ...
    def AddRenderPassToBack(self: DeviceManager, renderPass: IRenderPass) -> None: ...
    def RemoveRenderPass(self: DeviceManager, renderPass: IRenderPass) -> None: ...
    def RunMessageLoop(self: DeviceManager) -> None: ...
    def GetWindowDimensions(self: DeviceManager) -> tuple[int, int]: ...
    def GetDPIScaleInfo(self: DeviceManager) -> tuple[float, float]: ...
    def GetDeviceParams(self: DeviceManager) -> DeviceCreationParameters: ...
    def GetAverageFrameTimeSeconds(self: DeviceManager) -> float: ...
    def GetPreviousFrameTimestamp(self: DeviceManager) -> float: ...
    def SetFrameTimeUpdateInterval(self: DeviceManager, seconds: float) -> None: ...
    def IsVsyncEnabled(self: DeviceManager) -> bool: ...
    def SetVsyncEnabled(self: DeviceManager, enabled: bool) -> None: ...
    def ReportLiveObjects(self: DeviceManager) -> None: ...
    def SetEnableRenderDuringWindowMovement(self: DeviceManager, val: bool) -> None: ...
    def IsWindowFocused(self: DeviceManager) -> bool: ...
    def IsWindowVisible(self: DeviceManager) -> bool: ...
    def RenderNextFrameWhileUnfocused(self: DeviceManager) -> None: ...
    def GetFrameIndex(self: DeviceManager) -> int: ...
    def GetCurrentBackBuffer(self: DeviceManager) -> Texture: ...
    def GetBackBuffer(self: DeviceManager, index: int) -> Texture: ...
    def GetCurrentBackBufferIndex(self: DeviceManager) -> int: ...
    def GetBackBufferCount(self: DeviceManager) -> int: ...
    def GetCurrentFramebuffer(self: DeviceManager, withDepth: bool = True) -> Framebuffer: ...
    def GetFramebuffer(self: DeviceManager, index: int, withDepth: bool = True) -> Framebuffer: ...
    def GetDepthBuffer(self: DeviceManager) -> Texture: ...
    def GetDevice(self: DeviceManager) -> Device: ...
    def GetRendererString(self: DeviceManager) -> str: ...
    def GetGraphicsAPI(self: DeviceManager) -> GraphicsAPI: ...
    def SetWindowTitle(self: DeviceManager, title: str) -> None: ...
    def SetInformativeWindowTitle(self: DeviceManager, applicationName: str, includeFramerate: bool = True, extraInfo: Optional[str] = None) -> None: ...
    def GetWindowTitle(self: DeviceManager) -> str: ...
    def IsVulkanInstanceExtensionEnabled(self: DeviceManager, extensionName: str) -> bool: ...
    def IsVulkanDeviceExtensionEnabled(self: DeviceManager, extensionName: str) -> bool: ...
    def IsVulkanLayerEnabled(self: DeviceManager, layerName: str) -> bool: ...
    def GetEnabledVulkanInstanceExtensions(self: DeviceManager) -> list[str]: ...
    def GetEnabledVulkanDeviceExtensions(self: DeviceManager) -> list[str]: ...
    def GetEnabledVulkanLayers(self: DeviceManager) -> list[str]: ...
    def Shutdown(self: DeviceManager) -> None: ...
